### ISSUE TITLE
CocoaPods could not find compatible versions for pod "react-native-mock-location-detector"

### ISSUE THREAD

**Issue by mangjuned** [jpudysz/react-native-turbo-mock-location-detector#10]
```
yarn add react-native-turbo-mock-location-detector
cd ios && pod install
```

error : ```CocoaPods could not find compatible versions for pod "react-native-mock-location-detector"```

react native version: 0.72.5

**Comment by jpudysz** [comment]
Thank you for the report, I was able to reproduce it. Patch will land in a second

**Comment by mangjuned** [comment]
i tried change 
```s.platforms  = { :ios => "13.0" }```
 to 
 ```s.platforms = { :ios => "11.0" }```
 at ```/node_module/react-native-turbo-mock-location-detector/react-native-mock-location-detector.podspec```

and it's works!

**Comment by jpudysz** [comment]
Can you try with:

```
s.platforms    = { :ios => min_ios_version_supported }
```

**Comment by mangjuned** [comment]
> Can you try with:
> 
> ```
> s.platforms    = { :ios => min_ios_version_supported }
> ```

yes it's work, i've updated my pr. thankyou

**Comment by jpudysz** [comment]
Perfect, thank you for the contribution 🙏  will publish new version in a minutes

**Comment by AFoaad** [comment]
I'm getting error relative to this,

`
Invalid react-native-mock-location-detector.podspec file: undefined local variable or method  min_ios_version_supported for Pod:Module.

node_modules/react-native-turbo-mock-location-detector/react-native-mock-location-detector.podspec:13
 
 >    s.platforms    = { :ios => min_ios_version_supported }
     s.source       = { :git => "https://github.com/jpudysz/react-native-turbo-mock-location-detector.git", :tag => "#{s.version}" }
`

here is my react native info

System:
    OS: macOS 12.7.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 101.32 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 33
      Build Tools: 29.0.0, 29.0.1, 29.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.11005911
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.10 => 0.70.10
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
