### ISSUE TITLE
Update Readme.md for example import library command.

### ISSUE THREAD

**Issue by m00kid** [jpudysz/react-native-turbo-mock-location-detector#6]
Update the docs to say import 

`import {
  isMockingLocation,
  MockLocationDetectorErrorCode,
  MockLocationDetectorError,
} from 'react-native-turbo-mock-location-detector';
`

instead of 

`import {
  isMockingLocation,
  MockLocationDetectorErrorCode,
  MockLocationDetectorError,
} from 'react-native-mock-location-detector';`

**Comment by jpudysz** [comment]
Hey, thanks for the report. It's because of the https://github.com/jpudysz/react-native-turbo-mock-location-detector/pull/4 .
I will change and release new version when RN 0.72 lands (most likely this week)

**Comment by flexingCode** [comment]
Hey @jpudysz the RN 0.72.0 is now available :D

**Comment by jpudysz** [comment]
I'm working on new version 🙏

**Comment by jpudysz** [comment]
Opened PR #8, should release soon

**Comment by jpudysz** [comment]
I've published new version 2.2.0
