### ISSUE TITLE
Why can use with react native CLI Project

### ISSUE THREAD

**Issue by flexingCode** [jpudysz/react-native-turbo-mock-location-detector#7]
Hi, when i install the dependecy and want to use it, i get:

`Error: The package 'react-native-mock-location-detector' doesn't seem to be linked. Make sure:

- You have run pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow`

**Comment by jpudysz** [comment]
Hello, thanks for the report. It's a known issue due to last PR. I'm working on new version with support for React Native 0.72.

**Comment by jpudysz** [comment]
Opened PR #8

**Comment by jpudysz** [comment]
I've published new version 2.2.0
