### ISSUE TITLE
Is it possible to be a listener?

### ISSUE THREAD

**Issue by erennyuksell** [jpudysz/react-native-turbo-mock-location-detector#9]
Is it possible to have a listener that listens for location mocked while the app is in use?

**Comment by jpudysz** [comment]
Hello @erennyuksell , yes it's possible, I can see 2 options:

- use `AppState` to re-check if user enabled location mocking while your app was in the background (and then returned to foreground): https://reactnative.dev/docs/appstate

- use `setInterval` which will periodically check if location is mocked:

```tsx
useEffect(() => {
    const intervalId = setInterval(() => {
         // check once per 10 seconds
         isMockingLocation()
            .then(() => {})
            .catch(() => {})
    }, 10 * 1000)

   return () => clearInterval(intervalId)
}, [])
```

**Comment by erennyuksell** [comment]
@jpudysz Thank you, I keep getting this " {"code": "2", "message": "Couldn't determine if location is mocked"}" error, why?

**Comment by jpudysz** [comment]
@erennyuksell please check `README.md` with all required steps. There is a description when you can get `Couldn't determine if location is mocked` error

**Comment by erennyuksell** [comment]
This is my androidManifest
![image](https://github.com/jpudysz/react-native-turbo-mock-location-detector/assets/43651689/5907a284-309c-480b-b353-0965f60739e0)

and my code
![image](https://github.com/jpudysz/react-native-turbo-mock-location-detector/assets/43651689/b3f45018-0f85-4d92-ab7e-4fd49cbb45c9)

Am i doing something wrong? Thank you for your answer.

**Comment by jpudysz** [comment]
Can you try to run my example?

https://github.com/jpudysz/react-native-turbo-mock-location-detector/tree/main/example

**Comment by erennyuksell** [comment]
I will try. by the way my environment
React-native:0.69.12
react-native-turbo-mock-location-detector: 1.2.0
newArchEnabled=false

**Comment by erennyuksell** [comment]
Since I also need location information, I decided to use this package https://github.com/Agontuk/react-native-geolocation-service
